//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace joystickCombiner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string leftJoystick {
            get {
                return ((string)(this["leftJoystick"]));
            }
            set {
                this["leftJoystick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string rightJoystick {
            get {
                return ((string)(this["rightJoystick"]));
            }
            set {
                this["rightJoystick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string leftRudder {
            get {
                return ((string)(this["leftRudder"]));
            }
            set {
                this["leftRudder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string rightRudder {
            get {
                return ((string)(this["rightRudder"]));
            }
            set {
                this["rightRudder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte mode1Weight {
            get {
                return ((byte)(this["mode1Weight"]));
            }
            set {
                this["mode1Weight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public byte mode2Weight {
            get {
                return ((byte)(this["mode2Weight"]));
            }
            set {
                this["mode2Weight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public byte mode3Weight {
            get {
                return ((byte)(this["mode3Weight"]));
            }
            set {
                this["mode3Weight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte active {
            get {
                return ((byte)(this["active"]));
            }
            set {
                this["active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autostart {
            get {
                return ((bool)(this["autostart"]));
            }
            set {
                this["autostart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte axisXAxis {
            get {
                return ((byte)(this["axisXAxis"]));
            }
            set {
                this["axisXAxis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte axisXMethod {
            get {
                return ((byte)(this["axisXMethod"]));
            }
            set {
                this["axisXMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte axisXChange {
            get {
                return ((byte)(this["axisXChange"]));
            }
            set {
                this["axisXChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte axisYAxis {
            get {
                return ((byte)(this["axisYAxis"]));
            }
            set {
                this["axisYAxis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte axisYMethod {
            get {
                return ((byte)(this["axisYMethod"]));
            }
            set {
                this["axisYMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte axisYChange {
            get {
                return ((byte)(this["axisYChange"]));
            }
            set {
                this["axisYChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte axisTwistAxis {
            get {
                return ((byte)(this["axisTwistAxis"]));
            }
            set {
                this["axisTwistAxis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte axisTwistMethod {
            get {
                return ((byte)(this["axisTwistMethod"]));
            }
            set {
                this["axisTwistMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte axisTwistChange {
            get {
                return ((byte)(this["axisTwistChange"]));
            }
            set {
                this["axisTwistChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte axisThrottleAxis {
            get {
                return ((byte)(this["axisThrottleAxis"]));
            }
            set {
                this["axisThrottleAxis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte axisThrottleMethod {
            get {
                return ((byte)(this["axisThrottleMethod"]));
            }
            set {
                this["axisThrottleMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte axisThrottleChange {
            get {
                return ((byte)(this["axisThrottleChange"]));
            }
            set {
                this["axisThrottleChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte axisRotary1Axis {
            get {
                return ((byte)(this["axisRotary1Axis"]));
            }
            set {
                this["axisRotary1Axis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte axisRotary1Method {
            get {
                return ((byte)(this["axisRotary1Method"]));
            }
            set {
                this["axisRotary1Method"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte axisRotary1Change {
            get {
                return ((byte)(this["axisRotary1Change"]));
            }
            set {
                this["axisRotary1Change"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte axisRotary2Axis {
            get {
                return ((byte)(this["axisRotary2Axis"]));
            }
            set {
                this["axisRotary2Axis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte axisRotary2Method {
            get {
                return ((byte)(this["axisRotary2Method"]));
            }
            set {
                this["axisRotary2Method"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte axisRotary2Change {
            get {
                return ((byte)(this["axisRotary2Change"]));
            }
            set {
                this["axisRotary2Change"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte axisSliderAxis {
            get {
                return ((byte)(this["axisSliderAxis"]));
            }
            set {
                this["axisSliderAxis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte axisSliderMethod {
            get {
                return ((byte)(this["axisSliderMethod"]));
            }
            set {
                this["axisSliderMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte axisSliderChange {
            get {
                return ((byte)(this["axisSliderChange"]));
            }
            set {
                this["axisSliderChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte axisLeftToeAxis {
            get {
                return ((byte)(this["axisLeftToeAxis"]));
            }
            set {
                this["axisLeftToeAxis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte axisLeftToeMethod {
            get {
                return ((byte)(this["axisLeftToeMethod"]));
            }
            set {
                this["axisLeftToeMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte axisLeftToeChange {
            get {
                return ((byte)(this["axisLeftToeChange"]));
            }
            set {
                this["axisLeftToeChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte axisRightToeAxis {
            get {
                return ((byte)(this["axisRightToeAxis"]));
            }
            set {
                this["axisRightToeAxis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte axisRightToeMethod {
            get {
                return ((byte)(this["axisRightToeMethod"]));
            }
            set {
                this["axisRightToeMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte axisRightToeChange {
            get {
                return ((byte)(this["axisRightToeChange"]));
            }
            set {
                this["axisRightToeChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte axisRudderAxis {
            get {
                return ((byte)(this["axisRudderAxis"]));
            }
            set {
                this["axisRudderAxis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte axisRudderMethod {
            get {
                return ((byte)(this["axisRudderMethod"]));
            }
            set {
                this["axisRudderMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte axisRudderChange {
            get {
                return ((byte)(this["axisRudderChange"]));
            }
            set {
                this["axisRudderChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool axisXCentered {
            get {
                return ((bool)(this["axisXCentered"]));
            }
            set {
                this["axisXCentered"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool axisYCentered {
            get {
                return ((bool)(this["axisYCentered"]));
            }
            set {
                this["axisYCentered"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool axisTwistCentered {
            get {
                return ((bool)(this["axisTwistCentered"]));
            }
            set {
                this["axisTwistCentered"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool axisThrottleCentered {
            get {
                return ((bool)(this["axisThrottleCentered"]));
            }
            set {
                this["axisThrottleCentered"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool axisRotary1Centered {
            get {
                return ((bool)(this["axisRotary1Centered"]));
            }
            set {
                this["axisRotary1Centered"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool axisRotary2Centered {
            get {
                return ((bool)(this["axisRotary2Centered"]));
            }
            set {
                this["axisRotary2Centered"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool axisSliderCentered {
            get {
                return ((bool)(this["axisSliderCentered"]));
            }
            set {
                this["axisSliderCentered"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool axisLeftToeCentered {
            get {
                return ((bool)(this["axisLeftToeCentered"]));
            }
            set {
                this["axisLeftToeCentered"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool axisRightToeCentered {
            get {
                return ((bool)(this["axisRightToeCentered"]));
            }
            set {
                this["axisRightToeCentered"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool axisRudderCentered {
            get {
                return ((bool)(this["axisRudderCentered"]));
            }
            set {
                this["axisRudderCentered"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public short changeInterval {
            get {
                return ((short)(this["changeInterval"]));
            }
            set {
                this["changeInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte mode1Button {
            get {
                return ((byte)(this["mode1Button"]));
            }
            set {
                this["mode1Button"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte mode2Button {
            get {
                return ((byte)(this["mode2Button"]));
            }
            set {
                this["mode2Button"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte mode3Button {
            get {
                return ((byte)(this["mode3Button"]));
            }
            set {
                this["mode3Button"] = value;
            }
        }
    }
}
